import { CityLocation } from '../types';

export const CITIES_DATABASE: CityLocation[] = [
  // Lokasi Fokus KUA Kecamatan Gerung & Lombok Barat NTB
  {
    name: 'Gerung (KUA Kec. Gerung Lobar)',
    country: 'Indonesia',
    latitude: -(8 + 41 / 60), // 8° 41' LS
    longitude: 116 + 7 / 60,  // 116° 07' BT
    latDeg: 8,
    latMin: 41,
    latDir: 'S',
    lonDeg: 116,
    lonMin: 7,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  // Kitab Focal Locations (Mataram & Lombok NTB, Kediri Lobar, Jeringo, Ampenan)
  {
    name: 'Mataram (Lombok)',
    country: 'Indonesia',
    latitude: -(8 + 36 / 60), // 8° 36' LS
    longitude: 116 + 8 / 60,  // 116° 08' BT
    latDeg: 8,
    latMin: 36,
    latDir: 'S',
    lonDeg: 116,
    lonMin: 8,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Lombok (Jeringo Gunungsari)',
    country: 'Indonesia',
    latitude: -(8 + 32.24 / 60), // 8° 32.24' LS (Hal. 118 Kitab)
    longitude: 116 + 7.55 / 60,  // 116° 07.55' BT
    latDeg: 8,
    latMin: 32,
    latSec: 14,
    latDir: 'S',
    lonDeg: 116,
    lonMin: 7,
    lonSec: 33,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Kediri Lobar (Tgh. Ibrahim Al-Khalidy)',
    country: 'Indonesia',
    latitude: -(8 + 39 / 60),
    longitude: 116 + 10 / 60,
    latDeg: 8,
    latMin: 39,
    latDir: 'S',
    lonDeg: 116,
    lonMin: 10,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Ampenan',
    country: 'Indonesia',
    latitude: -(8 + 34 / 60), // 8° 34' LS (Hal. 46 Kitab)
    longitude: 116 + 5 / 60,  // 116° 05' BT
    latDeg: 8,
    latMin: 34,
    latDir: 'S',
    lonDeg: 116,
    lonMin: 5,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Selong (Lombok Timur)',
    country: 'Indonesia',
    latitude: -(8 + 38 / 60),
    longitude: 116 + 30 / 60,
    latDeg: 8,
    latMin: 38,
    latDir: 'S',
    lonDeg: 116,
    lonMin: 30,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Sumbawa Besar',
    country: 'Indonesia',
    latitude: -(8 + 30 / 60),
    longitude: 117 + 25 / 60,
    latDeg: 8,
    latMin: 30,
    latDir: 'S',
    lonDeg: 117,
    lonMin: 25,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Bima',
    country: 'Indonesia',
    latitude: -(8 + 27 / 60),
    longitude: 118 + 45 / 60,
    latDeg: 8,
    latMin: 27,
    latDir: 'S',
    lonDeg: 118,
    lonMin: 45,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Dompu',
    country: 'Indonesia',
    latitude: -(8 + 30 / 60),
    longitude: 118 + 28 / 60,
    latDeg: 8,
    latMin: 30,
    latDir: 'S',
    lonDeg: 118,
    lonMin: 28,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },

  // Pusat Islam Dunia
  {
    name: 'Makkah Al-Mukarramah',
    country: 'Saudi Arabia',
    latitude: 21 + 25 / 60 + 21 / 3600,
    longitude: 39 + 49 / 60 + 34 / 3600,
    latDeg: 21,
    latMin: 25,
    latDir: 'U',
    lonDeg: 39,
    lonMin: 49,
    lonDir: 'T',
    timezone: 3,
    timezoneName: 'AST'
  },
  {
    name: 'Madinah Al-Munawwarah',
    country: 'Saudi Arabia',
    latitude: 24 + 28 / 60,
    longitude: 39 + 36 / 60,
    latDeg: 24,
    latMin: 28,
    latDir: 'U',
    lonDeg: 39,
    lonMin: 36,
    lonDir: 'T',
    timezone: 3,
    timezoneName: 'AST'
  },
  {
    name: 'Al-Quds (Jerusalem)',
    country: 'Palestine',
    latitude: 31 + 46 / 60,
    longitude: 35 + 14 / 60,
    latDeg: 31,
    latMin: 46,
    latDir: 'U',
    lonDeg: 35,
    lonMin: 14,
    lonDir: 'T',
    timezone: 3,
    timezoneName: 'EET'
  },

  // Major Indonesian Cities
  {
    name: 'Jakarta (Tanjung Priok)',
    country: 'Indonesia',
    latitude: -(6 + 10 / 60),
    longitude: 106 + 49 / 60,
    latDeg: 6,
    latMin: 10,
    latDir: 'S',
    lonDeg: 106,
    lonMin: 49,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Bogor',
    country: 'Indonesia',
    latitude: -(6 + 37 / 60),
    longitude: 106 + 48 / 60,
    latDeg: 6,
    latMin: 37,
    latDir: 'S',
    lonDeg: 106,
    lonMin: 48,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Surabaya',
    country: 'Indonesia',
    latitude: -(7 + 15 / 60),
    longitude: 112 + 45 / 60,
    latDeg: 7,
    latMin: 15,
    latDir: 'S',
    lonDeg: 112,
    lonMin: 45,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Gresik (Manyar & Condrodipo)',
    country: 'Indonesia',
    latitude: -(7 + 10 / 60),
    longitude: 112 + 40 / 60,
    latDeg: 7,
    latMin: 10,
    latDir: 'S',
    lonDeg: 112,
    lonMin: 40,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Bandung',
    country: 'Indonesia',
    latitude: -(6 + 57 / 60),
    longitude: 107 + 37 / 60,
    latDeg: 6,
    latMin: 57,
    latDir: 'S',
    lonDeg: 107,
    lonMin: 37,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Semarang',
    country: 'Indonesia',
    latitude: -(7 + 0 / 60),
    longitude: 110 + 24 / 60,
    latDeg: 7,
    latMin: 0,
    latDir: 'S',
    lonDeg: 110,
    lonMin: 24,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Yogyakarta',
    country: 'Indonesia',
    latitude: -(7 + 48 / 60),
    longitude: 110 + 24 / 60,
    latDeg: 7,
    latMin: 48,
    latDir: 'S',
    lonDeg: 110,
    lonMin: 24,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Surakarta (Solo)',
    country: 'Indonesia',
    latitude: -(7 + 35 / 60),
    longitude: 110 + 48 / 60,
    latDeg: 7,
    latMin: 35,
    latDir: 'S',
    lonDeg: 110,
    lonMin: 48,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Malang',
    country: 'Indonesia',
    latitude: -(7 + 59 / 60),
    longitude: 112 + 36 / 60,
    latDeg: 7,
    latMin: 59,
    latDir: 'S',
    lonDeg: 112,
    lonMin: 36,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Banda Aceh',
    country: 'Indonesia',
    latitude: 5 + 35 / 60,
    longitude: 95 + 20 / 60,
    latDeg: 5,
    latMin: 35,
    latDir: 'U',
    lonDeg: 95,
    lonMin: 20,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Medan',
    country: 'Indonesia',
    latitude: 3 + 38 / 60,
    longitude: 98 + 38 / 60,
    latDeg: 3,
    latMin: 38,
    latDir: 'U',
    lonDeg: 98,
    lonMin: 38,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Padang',
    country: 'Indonesia',
    latitude: -(0 + 57 / 60),
    longitude: 100 + 21 / 60,
    latDeg: 0,
    latMin: 57,
    latDir: 'S',
    lonDeg: 100,
    lonMin: 21,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Palembang',
    country: 'Indonesia',
    latitude: -(2 + 59 / 60),
    longitude: 104 + 47 / 60,
    latDeg: 2,
    latMin: 59,
    latDir: 'S',
    lonDeg: 104,
    lonMin: 47,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Pontianak',
    country: 'Indonesia',
    latitude: -(0 + 5 / 60),
    longitude: 109 + 22 / 60,
    latDeg: 0,
    latMin: 5,
    latDir: 'S',
    lonDeg: 109,
    lonMin: 22,
    lonDir: 'T',
    timezone: 7,
    timezoneName: 'WIB'
  },
  {
    name: 'Banjarmasin',
    country: 'Indonesia',
    latitude: -(3 + 22 / 60),
    longitude: 114 + 40 / 60,
    latDeg: 3,
    latMin: 22,
    latDir: 'S',
    lonDeg: 114,
    lonMin: 40,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Balikpapan',
    country: 'Indonesia',
    latitude: -(1 + 13 / 60),
    longitude: 116 + 51 / 60,
    latDeg: 1,
    latMin: 13,
    latDir: 'S',
    lonDeg: 116,
    lonMin: 51,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Samarinda',
    country: 'Indonesia',
    latitude: -(0 + 28 / 60),
    longitude: 117 + 11 / 60,
    latDeg: 0,
    latMin: 28,
    latDir: 'S',
    lonDeg: 117,
    lonMin: 11,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Makassar (Ujung Pandang)',
    country: 'Indonesia',
    latitude: -(5 + 8 / 60),
    longitude: 119 + 27 / 60,
    latDeg: 5,
    latMin: 8,
    latDir: 'S',
    lonDeg: 119,
    lonMin: 27,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Manado',
    country: 'Indonesia',
    latitude: 1 + 33 / 60,
    longitude: 124 + 53 / 60,
    latDeg: 1,
    latMin: 33,
    latDir: 'U',
    lonDeg: 124,
    lonMin: 53,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Denpasar (Bali)',
    country: 'Indonesia',
    latitude: -(8 + 37 / 60),
    longitude: 115 + 13 / 60,
    latDeg: 8,
    latMin: 37,
    latDir: 'S',
    lonDeg: 115,
    lonMin: 13,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Kupang (NTT)',
    country: 'Indonesia',
    latitude: -(10 + 12 / 60),
    longitude: 123 + 35 / 60,
    latDeg: 10,
    latMin: 12,
    latDir: 'S',
    lonDeg: 123,
    lonMin: 35,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'WITA'
  },
  {
    name: 'Ambon (Maluku)',
    country: 'Indonesia',
    latitude: -(3 + 42 / 60),
    longitude: 128 + 10 / 60,
    latDeg: 3,
    latMin: 42,
    latDir: 'S',
    lonDeg: 128,
    lonMin: 10,
    lonDir: 'T',
    timezone: 9,
    timezoneName: 'WIT'
  },
  {
    name: 'Jayapura (Papua)',
    country: 'Indonesia',
    latitude: -(2 + 28 / 60),
    longitude: 140 + 38 / 60,
    latDeg: 2,
    latMin: 28,
    latDir: 'S',
    lonDeg: 140,
    lonMin: 38,
    lonDir: 'T',
    timezone: 9,
    timezoneName: 'WIT'
  },
  {
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    latitude: 3 + 8 / 60,
    longitude: 101 + 33 / 60,
    latDeg: 3,
    latMin: 8,
    latDir: 'U',
    lonDeg: 101,
    lonMin: 33,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'MYT'
  },
  {
    name: 'Singapore',
    country: 'Singapore',
    latitude: 1 + 21 / 60,
    longitude: 103 + 59 / 60,
    latDeg: 1,
    latMin: 21,
    latDir: 'U',
    lonDeg: 103,
    lonMin: 59,
    lonDir: 'T',
    timezone: 8,
    timezoneName: 'SGT'
  },
  {
    name: 'Cairo',
    country: 'Egypt',
    latitude: 30 + 8 / 60,
    longitude: 31 + 24 / 60,
    latDeg: 30,
    latMin: 8,
    latDir: 'U',
    lonDeg: 31,
    lonMin: 24,
    lonDir: 'T',
    timezone: 2,
    timezoneName: 'EET'
  },
  {
    name: 'Istanbul',
    country: 'Turkey',
    latitude: 40 + 59 / 60,
    longitude: 28 + 49 / 60,
    latDeg: 40,
    latMin: 59,
    latDir: 'U',
    lonDeg: 28,
    lonMin: 49,
    lonDir: 'T',
    timezone: 3,
    timezoneName: 'TRT'
  }
];

export const DEFAULT_CITY = CITIES_DATABASE[0]; // Mataram (Lombok)
